---
homebrew_repo: https://github.com/Homebrew/brew

homebrew_prefix: /usr/local
homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
homebrew_brew_bin_path: /usr/local/bin

homebrew_installed_packages:
  # dev
  - git
  - httpie
  - jq
  - python
  - python3
  # shell
  - coreutils
  - tree
  - csshx
  - fzf
  - wget
  - ssh-copy-id
  - openssl
  - pandoc
  - mas
  - molecule
  - prettyping

homebrew_upgrade_all_packages: no

homebrew_taps:
  - homebrew/bundle
  - homebrew/core
  - homebrew/cask

homebrew_cask_apps:
  # messaging
  - slack
  # browsers
  - google-chrome
  # utilities
  - copyclip
  # entertainment
  - spotify
  # devops
  - docker
  # ide
  - atom
  # terminal
  - hyper

mas_installed_app_ids: []

homebrew_cask_appdir: /Applications

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'
